quarkus.datasource.devservices.enabled=true
# changing shared has no effect on QuarkusTestResourceLifecycleManager
#quarkus.datasource.devservices.port=5432
quarkus.datasource.devservices.db-name=quarkus
quarkus.datasource.devservices.username=quarkus
quarkus.datasource.devservices.password=quarkus
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.schema-management.strategy = update

# has to be at least 2 for some reason I don't know
quarkus.datasource.jdbc.max-size=2



#%test.quarkus.datasource.jdbc.max-size=1